#!/usr/bin/env bash

BIN_FOLDER=$1
TOOL_NAME=${PWD##*/}
URL=https://gist.githubusercontent.com/yugoslavskiy/538a473222923a4b9ec1/raw/c995eb1f99e3994966c08817f45bd81143ebbb5e/generate_ssh_rsa_keys

curl -o ${BIN_FOLDER}/${TOOL_NAME} -O ${URL} && {
    chmod +x ${BIN_FOLDER}/${TOOL_NAME}
    echo "${BIN_FOLDER}" > current_installation
    exit 0
}

exit 104
