#!/usr/bin/env bash

BIN_FOLDER=$1
TOOL_NAME=${PWD##*/}
URL=https://gist.githubusercontent.com/yugoslavskiy/538a473222923a4b9ec1/raw/d8476fcbb006e4a3a70820db45445d2d544f2d7e/generate_ssh_rsa_keys.sh

curl -o ${BIN_FOLDER}/${TOOL_NAME} -O ${URL} && {
    chmod +x ${BIN_FOLDER}/${TOOL_NAME}
    echo "${BIN_FOLDER}" > current_installation
    exit 0
}

exit 104
