#!/usr/bin/env bash

SRC_FOLDER=$( cat current_installation | cut -d ':' -f 2 )
BIN_FOLDER=$( cat current_installation | cut -d ':' -f 1 )
TOOL_NAME=${PWD##*/}

rm -rfv ${SRC_FOLDER}/${TOOL_NAME} || exit 102
rm -fv ${BIN_FOLDER}/${TOOL_NAME} || exit 102
rm -fv current_installation || exit 102

exit 0
