#!/usr/bin/env bash

SRC_FOLDER=$( cat current_installation | cut -d ':' -f 2 )
BIN_FOLDER=$( cat current_installation | cut -d ':' -f 1 )
TOOL_NAME=${PWD##*/}

pushd ${SRC_FOLDER}/${TOOL_NAME} || exit 101
for SCRIPT in $(ls *.sh)
do
	LINK_NAME=$( echo ${SCRIPT} | cut -d '.' -f 1 )
	rm -fv ${BIN_FOLDER}/${LINK_NAME} || exit 102
done
popd || exit 101

rm -rfv ${SRC_FOLDER}/${TOOL_NAME} || exit 102
rm -fv current_installation || exit 102

exit 0
