#!/usr/bin/env bash

BIN_FOLDER=$1
SRC_FOLDER=$2
TOOL_NAME=${PWD##*/}

git clone https://github.com/wpscanteam/wpscan.git ${SRC_FOLDER}/${TOOL_NAME} || exit 105

pushd ${SRC_FOLDER}/${TOOL_NAME} || exit 101
gem install bundler || exit 111
bundle install --without test || exit 110
popd || exit 101

file=${BIN_FOLDER}/${TOOL_NAME};
cat <<EOF > "${file}" || exit 108
#!/usr/bin/env bash

cd ${SRC_FOLDER}/${TOOL_NAME} && ruby wpscan.rb "\$@"
EOF
chmod +x "${file}" || exit 109

echo "${BIN_FOLDER}:${SRC_FOLDER}" > current_installation

exit 0
