#!/usr/bin/env bash

BIN_FOLDER=$1
SRC_FOLDER=$2
TOOL_NAME=${PWD##*/}

git clone https://github.com/byt3bl33d3r/CrackMapExec.git ${SRC_FOLDER}/${TOOL_NAME} || exit 105

pushd ${SRC_FOLDER}/${TOOL_NAME} || exit 101
git pull || exit 116
pip install -r requirements.txt || exit 102105
popd || exit 101

file=${BIN_FOLDER}/${TOOL_NAME};
cat <<EOF > "${file}" || exit 108
#!/usr/bin/env bash

cd ${SRC_FOLDER}/${TOOL_NAME} && python crackmapexec.py "\$@"
EOF
chmod +x "${file}" || exit 109

echo "${BIN_FOLDER}:${SRC_FOLDER}" > current_installation

exit 0
