#!/usr/bin/env bash

BIN_FOLDER=$1
SRC_FOLDER=$2

# Name of the directory = it name of future ``$SRC_FOLDER'' directory (with git-repo) = name for link in ``$BIN_FOLDER''
TOOL_NAME=${PWD##*/}

#
# CLONE REPO
#

git clone https://github.com/wpscanteam/wpscan.git ${SRC_FOLDER}/${TOOL_NAME} || exit 105

#
# GO TO REPO
#

pushd ${SRC_FOLDER}/${TOOL_NAME} || exit 101

#
# RUN COMMANDS IN REPO (if needed)
#

gem install bundler || exit 111
bundle install --without test || exit 110

popd || exit 101

# this line helps for update and remove repo in future
echo "${BIN_FOLDER}:${SRC_FOLDER}" > current_installation

#
# CREATE LINK / SCRIPT
#

file=${BIN_FOLDER}/${TOOL_NAME};
cat <<EOF > "${file}" || exit 108
#!/usr/bin/env bash

cd ${SRC_FOLDER}/${TOOL_NAME} && ruby wpscan.rb "\$@"
EOF
chmod +x "${file}" || exit 109

exit 0
